# ver 1.0
---

blueprint:
  source_url: https://raw.githubusercontent.com/mstipanov/Home-Assistant-Blueprints/master/phillips_hue_dimmer_room_z2m_bound.yaml

  name: Zigbee2MQTT - Phillips HUE Dimmer - 4 Button Remote - Room - Bound

  description: >-
    This automation configures Phillips HUE Dimmer switch to my default room setup connected through Zigbee2MQTT when
    the light is bound to the switch using Zigbee2MQTT bind facility.

  domain: automation

  input:
    switch_device:
      name: Phillips HUE Dimmer remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          multiple: false
          filter:
            - integration: mqtt
              manufacturer: Philips
              model: Hue dimmer switch
    light_entity:
      description: Light entity to turn on or off.
      name: Light entity
      selector:
        entity:
          domain: light
    cover_entity:
      description: Cover entity to open or close.
      name: (Optional) Cover entity
      default: {}
      selector:
        entity:
          domain: cover

mode: parallel
max_exceeded: silent

triggers:
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: on_press_release
    trigger: device
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: on_hold
    trigger: device
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: off_press_release
    trigger: device
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: off_hold
    trigger: device
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: up_press_release
    trigger: device
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: down
    trigger: device
  - domain: mqtt
    device_id: !input switch_device
    type: action
    subtype: up_hold
    trigger: device

action:
  - choose:
      # Short-Press the on button
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.payload == 'on_press_release' }}"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input light_entity
                    state:
                      - "on"
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 100
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input light_entity
                    state:
                      - "on"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light_entity

      # Long-Press the on button
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'on_hold' }}"
        sequence:
          - service: pyscript.cover_open
            metadata: {}
            data:
              entity_id: !input cover_entity

      # Short-Press the off button
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'off_press_release' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
            metadata: {}
            data: {}

      # Long-Press the off button
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'off_hold' }}"
        sequence:
          - service: pyscript.cover_close
            metadata: {}
            data:
              entity_id: !input cover_entity

      # Long-Press the up button
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'up_hold' }}"
        sequence:
          - service: light.turn_on
            data:
              kelvin: 3800
              brightness_pct: 100
              color_name: white
            target:
              entity_id: !input light_entity

    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []
